apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: activemq-artemis-operator.v0.8.0
  namespace: placeholder
  annotations:
    categories: "Messaging"
    certified: "false"
    description: ActiveMQ Artemis Operator can deploy headless service environments which exposed each of the ports, along with the statefulset.
    containerImage: quay.io/artemiscloud/activemq-artemis-operator:latest
    createdAt: 2019-07-04T15:55:00Z
    support: Red Hat, Inc.
    tectonic-visibility: ocs
    alm-examples: >-
        [{
            "apiVersion": "broker.amq.io/v2alpha1",
            "kind": "ActiveMQArtemis",
            "metadata": {
                "name": "ex-aao",
                "labels": {
                    "ActiveMQArtemis": "ex-aao",
                    "application": "ex-aao-app"
                }
            },
            "spec": {
                "deploymentPlan": {
                    "size": 1,
                    "image": "registry.redhat.io/amq7/amq-broker:7.5"
                }
            }
        },
        {
            "apiVersion": "broker.amq.io/v2alpha1",
            "kind": "ActiveMQArtemisAddress",
            "metadata": {
                "name": "ex-aaoaddress",
                "labels": {
                    "ActiveMQArtemis": "ex-aao",
                    "application": "ex-aao-app"
                }
            },
            "spec": {
                "addressName": "myAddress0",
                "queueName": "myQueue0",
                "routingType": "anycast"
            }
        }]
  labels:
    operator-activemqartemis: "true"
spec:
  displayName: ActiveMQ Artemis
  description: ActiveMQ Artemis Operator deploys the ActiveMQ Artemis broker or brokers on OpenShift via a statefulset.
  keywords:
    - activemqartemis
    - operator
  version: 0.8.0
  maturity: alpha
  replaces: activemq-artemis-operator.v0.7.0
  maintainers:
    - name: Red Hat, Inc.
      email: rkieley@redhat.com
  provider:
    name: Red Hat, Inc.
  links:
    - name: Product Page
      url: https://access.redhat.com/products/red-hat-amq/
    - name: Documentation
      url: https://access.redhat.com/documentation/en-us/red_hat_amq/
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALGPC/xhBQAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAlywAAJcsBGkdkZgAAAAd0SU1FB+MDHQ02AU8UBK4AAASBSURBVFjDtZfNb1RlFMZ/7zt3vqCU0pSSQjMSbCHVRSEjq7aBhQvFsDBqJIYF/gGGxAUpREyMCG5YqCSuiDGGRE2NCxTRBgkJuGlKYpAOBW3NtJ22UzoznTv3du6d++FibsvQ6XzQ1rO899z3Oefc5zznvII6LRahCTgCHAIOAu3ANu91GpgEhoBbwLWuOJl6zhV1AO8F+oG3gU11xqsD3wMXuuI8XFMAsQhh4BzwHuBnbVYAvgDOdsXR6w4gFqET+BF4kY2x+8DrXXEe1QwgFuEA8CuwnY21Od3h1egkwxUD8DK/8z+AozugOaQl9PQmiJUF4P3zoQ0s+0rwJRv1QbQngQaglPidqwYuWjtp+eRzELIqmF0wyefzy7kVcira6XdLXfY58KlH7qKX12p/VWO7cvA1OgZ+wrVthM+HY1lIRXnKx7EsMpkMOVXFJ8AwDMJ+P3/3daw8zpLQ3ZtgZCmd0/W22r/jY6jpFLdv/o6xuFgGbrsuqqqyuJDhcTJZMR8XzgAIT+GmaonMcgUsC6H4sAsWPr+/DBxgMaciERhGnk2BwGoVAMj7BO2KJ681Fc6ZHCd18waIculYXFjAdoosU/buI9y6Ayu7gDUyQjqnVjoy5LgcVYDD9ZTemR4heeLlmmxvvHydzaEw8Y/OYt74ttaxhxTgpdIn4eOnCHR0epS2KmusrmOXyEh28Be0u4OEZmeYv/J1PeC4EFW8qbZszW8dY8v+A1U/zGsaqpYjr+lIn8QfDKEWTLg7yHz/ibr1QUBEKRmpT/6pmiWZTBIIhjBNk+f27CkBz6FqOq5tMzUxQbChgdYdO9YkUC40KquyY3MDO3cFED6J67hl4AiBkJKtzdtQAkGklGtWSQVIAa3L2T8aRQYDBNt2oTQ14Zgm2v17WKaJlsvhel1guRD2vjFmZzDj8WcGF5AVsQh3gbKfrvS+SeSzLxE+H//sb66m7euxe4o3gMoCsG4PED8JbR9+7EUUJHzsJKaU+FxorDgMbArGk1ng6BrG1cuVKjAsYhHeAa5ULFOgAdfMoRw8QsfAzzVY5ZJNp9GNPAKBbdtI0+RR3/OVAjghgWveDrf6mWauSEAvo+nJCbRslj+HhjAN42nwTBrDtpmfe4yanGFyfKxqN0vBVeltr9/VUjjda4amrU2EwmEiu3fj92ZBETyDYdkABPx+lGCIcDhcjYA/9EyRWmrDC8Dx1SbiEuH8mRT67AwCganrhID83BwA2kKGfKFQpMqWRppaWnAdG7/jYCRnV8O3BJxfuRFdBN5fL9vbvrpOY3c301e+IXvxVKXsL/UligtJqYJ84G2v62o117KqggOjUtBfaSntAP7QHbavtc/lnijO2HCl1ylvKX1QcS0fbieqOfwGNG/wbpqS8EpvgqGnAl7pFZ1kWEIPMLqB4KNe5kNlFVvNuzfBA0UQFcVrlbUOYEvAJQWipWV/psvp7Z284MIZF94AQnUCGwIGBJzvTTCyrtvxkt3ZRbPjchQ47EJUQGRpJAjIuhAXMAzckoKrPVPM13Puf2Qd6X5KXrjXAAAAAElFTkSuQmCC
      mediatype: image/png
  labels:
    alm-owner-amq-broker: activemq-artemis-operator
    operated-by: activemq-artemis-operator.v0.8.0
  selector:
    matchLabels:
      ActiveMQArtemis: ex-aao
      application: ex-aao-app
      operated-by: activemq-artemis-operator.v0.8.0
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: false
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
  customresourcedefinitions:
    owned:
      - name: activemqartemises.broker.amq.io
        version: v2alpha1
        versions:
          - name: v2alpha1
            served: true
            storage: true
          - name: v1alpha1
            served: false
            storage: false
        kind: ActiveMQArtemis
        description: An instance of Active MQ Artemis
        displayName: ActiveMQ Artemis
        resources:
          - kind: Service
            version: v1
          - kind: Route
            version: v1
          - kind: StatefulSet
            version: v1
          - kind: Secret
            version: v1
        specDescriptors:
          - description: The settings required for the broker to be deployed
            displayName: DeploymentPlan
            path: deploymentPlan
          - description: The number of broker pods to deploy
            displayName: Size
            path: size
          - description: The image used for the broker deployment
            displayName: Image
            path: image
          - description: If true require user password login credentials for broker protocol ports
            displayName: boolean
            path: requireLogin
          - description: If true brokers will cluster when scale > 1
            displayName: boolean
            path: clustered
          - description: If true use persistent volume via persistent volume claim for journal storage
            displayName: boolean
            path: persistenceEnabled
          - description: If aio use ASYNCIO, if nio use NIO for journal IO
            displayName: string
            path: journalType
          - description: If true migrate messages on scaledown
            displayName: boolean
            path: messageMigration
      - name: activemqartemisaddresses.broker.amq.io
        version: v2alpha1
        kind: ActiveMQArtemisAddress
        description: Adding and removing addresses via custom resource definitions
        displayName: ActiveMQ Artemis Address
        specDescriptors:
          - description: The Queue Name
            displayName: Queue Name
            path: queueName
          - description: The Address Name
            displayName: Address Name
            path: addressName
          - description: The Routing Type
            displayName: Routing Type
            path: routingType
      - name: activemqartemisscaledowns.broker.amq.io
        version: v2alpha1
        kind: ActiveMQArtemisScaledown
        description: Provides message migration on clustered broker scaledown
        displayName: ActiveMQ Artemis Scaledown
        specDescriptors:
          - displayName: Local Namespace Only
            path: localOnly
            description: Triggered by main ActiveMQArtemis CRD messageMigration entry
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: activemq-artemis-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - routes
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - broker.amq.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - "route.openshift.io"
              resources:
                - routes
                - routes/custom-host
                - routes/status
              verbs:
                - get
                - list
                - watch
                - create
                - delete

      deployments:
        - name: activemq-artemis-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: activemq-artemis-operator
            template:
              metadata:
                labels:
                  name: activemq-artemis-operator
              spec:
                serviceAccountName: activemq-artemis-operator
                containers:
                  - name: activemq-artemis-operator
                    # Replace this with the built image name
                    image: quay.io/artemiscloud/activemq-artemis-operator:0.8.0
                    command:
                      -  /home/activemq-artemis-operator/bin/entrypoint
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: "activemq-artemis-operator"
