apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: activemq-artemis-resources
      namespace: operator-lifecycle-manager
    data:
      clusterServiceVersions: |
        - apiVersion: operators.coreos.com/v1alpha1
          kind: ClusterServiceVersion
          metadata:
            name: activemq-artemis-operator.v0.4.0
            namespace: placeholder
            annotations:
              categories: "Messaging"
              certified: "false"
              description: ActiveMQ Artemis Operator can deploy headless service environments which exposed each of the ports, along with the statefulset.
              containerImage: activemq-artemis-operator:latest
              createdAt: 2019-03-20T20:48:22Z
              support: Red Hat, Inc.
              tectonic-visibility: ocs
              alm-examples: >-
                [{
                 		"apiVersion": "broker.amq.io/v1alpha1",
                 		"kind": "ActiveMQArtemis",
                 		"metadata": {
                 			"name": "example-activemqartemis",
                 			"labels": {
                 				"ActiveMQArtemis": "example-activemqartemis",
                 				"application": "example-activemqartemis-app"
                 			}
                 		},
                 		"spec": {
                 			"size": "4",
                 			"image": "registry.access.redhat.com/amq-broker-7/amq-broker-72-openshift:1.3-4"
                 		}
                 	},
                 	{
                 		"apiVersion": "broker.amq.io/v1alpha1",
                 		"kind": "ActiveMQArtemisAddress",
                 		"metadata": {
                 			"name": "example-activemqartemisaddress",
                 			"labels": {
                 				"ActiveMQArtemis": "example-activemqartemis",
                 				"application": "example-activemqartemis-app"
                 			}
                 		},
                 		"spec": {
                 			"statefulsetName": "example-activemqartemis-ss",
                 			"addressName": "myAddress0",
                 			"queueName": "myQueue0",
                 			"routingType": "anycast"
                 		}
                 	}
                 ]
          
            labels:
              operator-activemqartemis: "true"
          spec:
            displayName: ActiveMQ Artemis
            description: ActiveMQ Artemis Operator can deploy headless service environments which exposed each of the ports, along with the statefulset.
            keywords:
              - activemqartemis
              - operator
            version: 0.4.0
            maturity: alpha
            maintainers:
              - name: Red Hat, Inc.
                email: rkieley@redhat.com
            provider:
              name: Red Hat, Inc.
            links:
              - name: Product Page
                url: https://access.redhat.com/products/red-hat-amq/
              - name: Documentation
                url: https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/
            icon:
              - base64data: iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALGPC/xhBQAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAlywAAJcsBGkdkZgAAAAd0SU1FB+MDHQ02AU8UBK4AAASBSURBVFjDtZfNb1RlFMZ/7zt3vqCU0pSSQjMSbCHVRSEjq7aBhQvFsDBqJIYF/gGGxAUpREyMCG5YqCSuiDGGRE2NCxTRBgkJuGlKYpAOBW3NtJ22UzoznTv3du6d++FibsvQ6XzQ1rO899z3Oefc5zznvII6LRahCTgCHAIOAu3ANu91GpgEhoBbwLWuOJl6zhV1AO8F+oG3gU11xqsD3wMXuuI8XFMAsQhh4BzwHuBnbVYAvgDOdsXR6w4gFqET+BF4kY2x+8DrXXEe1QwgFuEA8CuwnY21Od3h1egkwxUD8DK/8z+AozugOaQl9PQmiJUF4P3zoQ0s+0rwJRv1QbQngQaglPidqwYuWjtp+eRzELIqmF0wyefzy7kVcira6XdLXfY58KlH7qKX12p/VWO7cvA1OgZ+wrVthM+HY1lIRXnKx7EsMpkMOVXFJ8AwDMJ+P3/3daw8zpLQ3ZtgZCmd0/W22r/jY6jpFLdv/o6xuFgGbrsuqqqyuJDhcTJZMR8XzgAIT+GmaonMcgUsC6H4sAsWPr+/DBxgMaciERhGnk2BwGoVAMj7BO2KJ681Fc6ZHCd18waIculYXFjAdoosU/buI9y6Ayu7gDUyQjqnVjoy5LgcVYDD9ZTemR4heeLlmmxvvHydzaEw8Y/OYt74ttaxhxTgpdIn4eOnCHR0epS2KmusrmOXyEh28Be0u4OEZmeYv/J1PeC4EFW8qbZszW8dY8v+A1U/zGsaqpYjr+lIn8QfDKEWTLg7yHz/ibr1QUBEKRmpT/6pmiWZTBIIhjBNk+f27CkBz6FqOq5tMzUxQbChgdYdO9YkUC40KquyY3MDO3cFED6J67hl4AiBkJKtzdtQAkGklGtWSQVIAa3L2T8aRQYDBNt2oTQ14Zgm2v17WKaJlsvhel1guRD2vjFmZzDj8WcGF5AVsQh3gbKfrvS+SeSzLxE+H//sb66m7euxe4o3gMoCsG4PED8JbR9+7EUUJHzsJKaU+FxorDgMbArGk1ng6BrG1cuVKjAsYhHeAa5ULFOgAdfMoRw8QsfAzzVY5ZJNp9GNPAKBbdtI0+RR3/OVAjghgWveDrf6mWauSEAvo+nJCbRslj+HhjAN42nwTBrDtpmfe4yanGFyfKxqN0vBVeltr9/VUjjda4amrU2EwmEiu3fj92ZBETyDYdkABPx+lGCIcDhcjYA/9EyRWmrDC8Dx1SbiEuH8mRT67AwCganrhID83BwA2kKGfKFQpMqWRppaWnAdG7/jYCRnV8O3BJxfuRFdBN5fL9vbvrpOY3c301e+IXvxVKXsL/UligtJqYJ84G2v62o117KqggOjUtBfaSntAP7QHbavtc/lnijO2HCl1ylvKX1QcS0fbieqOfwGNG/wbpqS8EpvgqGnAl7pFZ1kWEIPMLqB4KNe5kNlFVvNuzfBA0UQFcVrlbUOYEvAJQWipWV/psvp7Z284MIZF94AQnUCGwIGBJzvTTCyrtvxkt3ZRbPjchQ47EJUQGRpJAjIuhAXMAzckoKrPVPM13Puf2Qd6X5KXrjXAAAAAElFTkSuQmCC
                mediatype: image/png
            labels:
              alm-owner-amq-broker: activemq-artemis-operator
              operated-by: activemq-artemis-operator.v0.4.0
            selector:
              matchLabels:
                ActiveMQArtemis: example-activemqartemis
                application: example-activemqartemis-app
                operated-by: activemq-artemis-operator.v0.4.0
            installModes:
              - type: OwnNamespace
                supported: true
              - type: SingleNamespace
                supported: false
              - type: MultiNamespace
                supported: false
              - type: AllNamespaces
                supported: false
            customresourcedefinitions:
              owned:
                - name: activemqartemises.broker.amq.io
                  version: v1alpha1
                  kind: ActiveMQArtemis
                  description: An instance of Active MQ Artemis
                  displayName: ActiveMQ Artemis
                  resources:
                    - kind: Service
                      version: v1
                    - kind: Deployment
                      version: v1
                  specDescriptors:
                    - description: The desired number of member pods for ActiveMQArtemis mesh
                      displayName: Size
                      path: size
                    - description: The Image
                      displayName: Image
                      path: image
                - name: activemqartemisaddresses.broker.amq.io
                  version: v1alpha1
                  kind: ActiveMQArtemisAddress
                  description: Adding and removing queues via custom resource definitions
                  displayName: ActiveMQ Artemis Address
                  specDescriptors:
                    - description: The Statefulset Name
                      displayName: Statefulset Name
                      path: statefulsetName
                    - description: The Queue Name
                      displayName: Queue Name
                      path: queueName
                    - description: The Address Name
                      displayName: Address Name
                      path: addressName
                    - description: The Routing Type
                      displayName: Routing Type
                      path: routingType
          
          
            install:
              strategy: deployment
              spec:
                permissions:
                  - serviceAccountName: activemq-artemis-operator
                    rules:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                          - services
                          - endpoints
                          - persistentvolumeclaims
                          - events
                          - configmaps
                          - secrets
                        verbs:
                          - '*'
                      - apiGroups:
                          - ""
                        resources:
                          - namespaces
                        verbs:
                          - get
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - daemonsets
                          - replicasets
                          - statefulsets
                        verbs:
                          - '*'
                      - apiGroups:
                          - monitoring.coreos.com
                        resources:
                          - servicemonitors
                        verbs:
                          - get
                          - create
                      - apiGroups:
                          - broker.amq.io
                        resources:
                          - '*'
                        verbs:
                          - '*'
                deployments:
                  - name: activemq-artemis-operator
                    spec:
                      replicas: 1
                      selector:
                        matchLabels:
                          name: activemq-artemis-operator
                      template:
                        metadata:
                          labels:
                            name: activemq-artemis-operator
                        spec:
                          serviceAccountName: activemq-artemis-operator
                          containers:
                            - name: activemq-artemis-operator
                              # Replace this with the built image name
                              image: activemq-artemis-operator:latest
                              command:
                                - /usr/local/bin/entrypoint
                              imagePullPolicy: Always
                              env:
                                - name: WATCH_NAMESPACE
                                  valueFrom:
                                    fieldRef:
                                      fieldPath: metadata.namespace
                                - name: POD_NAME
                                  valueFrom:
                                    fieldRef:
                                      fieldPath: metadata.name
                                - name: OPERATOR_NAME
                                  value: "activemq-artemis-operator"
      customResourceDefinitions: |
        - apiVersion: apiextensions.k8s.io/v1beta1
          kind: CustomResourceDefinition
          metadata:
            creationTimestamp: null
            name: activemqartemises.broker.amq.io
          spec:
            group: broker.amq.io
            names:
              kind: ActiveMQArtemis
              listKind: ActiveMQArtemisList
              plural: activemqartemises
              singular: activemqartemis
            scope: Namespaced
            subresources:
              scale:
                specReplicasPath: .spec.replicas
                statusReplicasPath: .status.replicas
              status: {}
            validation:
              openAPIV3Schema:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  metadata:
                    type: object
                  spec:
                    properties:
                      image:
                        type: string
                    required:
                    - image
                    type: object
                  status:
                    type: object
            version: v1alpha1
            versions:
            - name: v1alpha1
              served: true
              storage: true
        - apiVersion: apiextensions.k8s.io/v1beta1
          kind: CustomResourceDefinition
          metadata:
            creationTimestamp: null
            name: activemqartemisaddresses.broker.amq.io
          spec:
            group: broker.amq.io
            names:
              kind: ActiveMQArtemisAddress
              listKind: ActiveMQArtemisAddressList
              plural: activemqartemisaddresses
              singular: activemqartemisaddress
            scope: Namespaced
            subresources:
              status: {}
            validation:
              openAPIV3Schema:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  metadata:
                    type: object
                  spec:
                    properties:
                      statefulsetName:
                        type: string
                      addressName:
                        type: string
                      queueName:
                        type: string
                      routingType:
                        type: string
                    required:
                      - addressName
                      - queueName
                      - routingType
                      - statefulsetName
                    type: object
                  status:
                    type: object
            version: v1alpha1
            versions:
            - name: v1alpha1
              served: true
              storage: true
      packages: >
        - #! package-manifest: deploy/catalog_resources/redhat/activemq-artemis-operator.v0.4.0.clusterserviceversion.yaml
          packageName: activemq-artemis-operator
          channels:
            - name: alpha
              currentCSV: activemq-artemis-operator.v0.4.0

  - apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: activemq-artemis-resources
      namespace: operator-lifecycle-manager
    spec:
      configMap: activemq-artemis-resources
      displayName: ActiveMQ Artemis Operator
      publisher: Red Hat
      sourceType: internal
    status:
      configMapReference:
        name: activemq-artemis-resources
        namespace: operator-lifecycle-manager
