apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 2
    image: placeholder
    persistenceEnabled: true
    messageMigration: true
  acceptors:
  - name: amqp
    protocols: amqp
    port: 5672
    sslEnabled: true
