apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: quay.io/artemiscloud/activemq-artemis-operator:latest
  acceptors:
  - name: amqp
    protocols: amqp
    port: 5672
    sslEnabled: true
