apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: placeholder
  addressSettings:
    applyRule: replace_all
    addressSetting:
    - match: '#'
      deadLetterAddress: DLQ
    - match: 'abc#'
      deadLetterAddress: DLQABC
      defaultConsumerWindowSize: 2048000
      maxSizeBytes: '10m'
    - match: 'jms'
      deadLetterAddress: jmsdlq



