apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: activemqartemises.broker.amq.io
spec:
  group: broker.amq.io
  names:
    kind: ActiveMQArtemis
    listKind: ActiveMQArtemisList
    plural: activemqartemises
    singular: activemqartemis
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
    status: {}
  validation:
    openAPIV3Schema:
      required:
        - spec
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          deploymentPlan:
            type: object
            properties:
              image:
                type: string
                description: The image used for the broker deployment
              size:
                type: integer
                minimum: 0
                maximum: 16
                description: The number of broker pods to deploy
              user:
                type: string
                description: User name for standard broker user. It is required for connecting to the broker. If left empty, it will be generated.
              password:
                type: string
                description: Password for standard broker user. It is required for connecting to the broker. If left empty, it will be generated.
              role:
                type: string
                description: Rolename for the given user
              requireLogin:
                type: boolean
                description: If true require user password login credentials for broker protocol ports
              clustered:
                type: boolean
                description: If true brokers will cluster when scale > 1
              clusterUser:
                type: string
                description: Username used for clustering
              clusterPassword:
                type: string
                description: Password used for clustering
              persistenceEnabled:
                type: boolean
                description: If true use persistent volume via persistent volume claim for journal storage
              journalType:
                type: string
                description: If aio use ASYNCIO, if nio use NIO for journal IO
              messageMigration:
                type: boolean
                description: If true migrate messages on scaledown
          acceptors:
            type: array
            description: Configuration of all acceptors
            minItems: 0
            items:
              type: object
              description: A single acceptor configuration
              properties:
                name:
                  type: string
                  description: The name of the acceptor
                port:
                  type: integer
                  description: Port number
                protocols:
                  type: string
                  description: The protocols to enable for this acceptor
                sslEnabled:
                  type: boolean
                  description: Whether or not to enable SSL on this port
                sslSecret:
                  type: string
                  description: Name of the secret to use for ssl information
                expose:
                  type: boolean
                  description: Whether or not to expose this port
          connectors:
            type: array
            description: Configuration of all connectors
            minItems: 0
            items:
              type: object
              description: A single connector configuration
              properties:
                name:
                  type: string
                  description: The name of the acceptor
                type:
                  type: string
                  description: The type either tcp or vm
                host:
                  type: string
                  description: Hostname or IP to connect to
                port:
                  type: integer
                  description: Port number
                sslEnabled:
                  type: boolean
                  description: Whether or not to enable SSL on this port
                sslSecret:
                  type: string
                  description: Name of the secret to use for ssl information
          console:
            type: object
            description: Configuration for the embedded web console
            properties:
              expose:
                type: boolean
                description: Whether or not to expose this port
              sslEnabled:
                type: boolean
                description: Whether or not to enable SSL on this port
              sslSecret:
                type: string
                description: Name of the secret to use for ssl information
              useClientAuth:
                type: boolean
                description: If the embedded server requires client authentication
        status:
          type: object
  version: v2alpha1
  versions:
  - name: v2alpha1
    served: true
    storage: true
  - name: v1alpha1
    served: false
    storage: false
