apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: activemqartemises.broker.amq.io
spec:
  group: broker.amq.io
  names:
    kind: ActiveMQArtemis
    listKind: ActiveMQArtemisList
    plural: activemqartemises
    singular: activemqartemis
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
    status: {}
  validation:
    openAPIV3Schema:
      required:
        - spec
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              type: string
            size:
              type: integer
              minimum: 1
              maximum: 16
              description: The number of activemqartemis pods to deploy
            persistent:
              type: boolean
            aio:
              type: boolean
            sslConfig:
              type: object
              description: Configuration of the AMQ SSL deployment
              required:
                - secretName
                - trustStoreFilename
                - trustStorePassword
                - keystoreFilename
                - keyStorePassword
              properties:
                secretName:
                  type: string
                  description:  Name of a secret containing SSL related files
                trustStoreFilename:
                  type: string
                  description:  SSL trust store filename
                trustStorePassword:
                  type: string
                  description:  SSL trust store password
                keystoreFilename:
                  type: string
                  description:  SSL key store filename
                keyStorePassword:
                  type: string
                  description:  Password for accessing SSL keystore
            clusterConfig:
              type: object
              description: Configuration of the AMQ cluster deployment
              required:
                - clusterUserName
                - clusterPassword
              properties:
                clusterUserName:
                  type: string
                  description:  Cluster user
                clusterPassword:
                  type: string
                  description: Cluster password
            commonConfig:
              type: object
              description: Common configuration of the AMQ
              required:
                - userName
                - password
              properties:
                userName:
                  type: string
                  description: User name for standard broker user. It is required for connecting to the broker. If left empty, it will be generated.
                password:
                  type: string
                  description: Password for standard broker user. It is required for connecting to the broker. If left empty, it will be generated.
          required:
          - image
          - size
          - commonConfig
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
