apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: activemqartemisaddresses.broker.amq.io
spec:
  group: broker.amq.io
  names:
    kind: ActiveMQArtemisAddress
    listKind: ActiveMQArtemisAddressList
    plural: activemqartemisaddresses
    singular: activemqartemisaddress
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha2
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            statefulsetName:
              type: string
            addressName:
              type: string
            queueName:
              type: string
            routingType:
              type: string
          required:
            - addressName
            - queueName
            - routingType
          type: object
        status:
          type: object
  versions:
  - name: v1alpha2
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false