apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: activemq-artemis-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ActiveMQArtemisAddress is the Schema for the activemqartemisaddresses
        API
      displayName: Active MQArtemis Address
      kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v1beta1
    - description: ActiveMQArtemisAddress is the Schema for the activemqartemisaddresses
        API
      displayName: Active MQArtemis Address
      kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v2alpha3
    - description: ActiveMQArtemisAddress is the Schema for the activemqartemisaddresses
        API
      displayName: Active MQArtemis Address
      kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v2alpha2
    - description: ActiveMQArtemisAddress is the Schema for the activemqartemisaddresses
        API
      displayName: Active MQArtemis Address
      kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v2alpha1
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v1beta2
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v1beta1
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha5
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha4
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha3
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha2
    - description: ActiveMQArtemis is the Schema for the activemqartemises API
      displayName: Active MQArtemis
      kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha1
    - description: ActiveMQArtemisScaledown is the Schema for the activemqartemisscaledowns
        API
      displayName: Active MQArtemis Scaledown
      kind: ActiveMQArtemisScaledown
      name: activemqartemisscaledowns.broker.amq.io
      version: v1beta1
    - description: ActiveMQArtemisScaledown is the Schema for the activemqartemisscaledowns
        API
      displayName: Active MQArtemis Scaledown
      kind: ActiveMQArtemisScaledown
      name: activemqartemisscaledowns.broker.amq.io
      version: v2alpha1
    - description: ActiveMQArtemisSecurity is the Schema for the activemqartemissecurities
        API
      displayName: Active MQArtemis Security
      kind: ActiveMQArtemisSecurity
      name: activemqartemissecurities.broker.amq.io
      version: v1beta1
    - description: ActiveMQArtemisSecurity is the Schema for the activemqartemissecurities
        API
      displayName: Active MQArtemis Security
      kind: ActiveMQArtemisSecurity
      name: activemqartemissecurities.broker.amq.io
      version: v1alpha1
  description: ArtemisCloud Operator manages ActiveMQ Artemis messaging broker in
    the cloud
  displayName: ArtemisCloud Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - messaging
  - cloud
  - kubernetes
  - artemis
  - integration
  links:
  - name: Activemq Artemis Operator
    url: https://activemq-artemis-operator.domain
  maintainers:
  - email: rkieley@redhat.com
    name: '''Roderick Kieley'
  - email: hgao@redhat.com
    name: Howard Gao
  - email: dbruscin@redhat.com'
    name: Domenico Francesco
  maturity: alpha
  provider:
    name: ArtemisCloud
    url: https://github.com/artemiscloud/activemq-artemis-operator
  version: 0.0.0
