apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-artemis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: activemq-artemis-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: activemq-artemis-operator
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level debug'
        command:
        - /home/activemq-artemis-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BROKER_IMAGE_211
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.0
        - name: BROKER_IMAGE_212
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.0
        - name: BROKER_IMAGE_213
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.0
        image: quay.io/artemiscloud/activemq-artemis-operator:0.16.0
        imagePullPolicy: Always
        name: activemq-artemis-operator
        resources: {}
      serviceAccountName: activemq-artemis-operator
