apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-artemis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: activemq-artemis-operator
  template:
    metadata:
      labels:
        name: activemq-artemis-operator
    spec:
      serviceAccountName: activemq-artemis-operator
      containers:
        - name: activemq-artemis-operator
          # Replace this with the built image name
          image: quay.io/artemiscloud/activemq-artemis-operator:0.9.2
          command:
            - /home/activemq-artemis-operator/bin/entrypoint
          args:
            # Explicitly set the logging level.
            # Valid values are debug, info, and error
            # from most to least
            - '--zap-level debug'
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "activemq-artemis-operator"
