apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-artemis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: activemq-artemis-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: activemq-artemis-operator
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level debug'
        - '--zap-encoder console'
        command:
        - /home/activemq-artemis-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2150
          value: quay.io/artemiscloud/activemq-artemis-broker-init:0.2.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2160
          value: quay.io/artemiscloud/activemq-artemis-broker-init:0.2.3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2150
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2160
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.1

        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2150_ppc64le
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2160_ppc64le
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2150_ppc64le
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes-openj9-11-rhel8:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2160_ppc64le
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes-openj9-11-rhel8:dev.latest

        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2150_s390x
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2160_s390x
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2150_s390x
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes-openj9-11-rhel8:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2160_s390x
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes-openj9-11-rhel8:dev.latest

        image: quay.io/artemiscloud/activemq-artemis-operator:dev.latest
        imagePullPolicy: Always
        name: activemq-artemis-operator
        resources: {}
      serviceAccountName: activemq-artemis-operator
