packageName: activemq-artemis
channels:
  - name: alpha
    currentCSV: activemq-artemis-operator.v0.9.1
  - name: stable-7.5-on-z
    currentCSV: activemq-artemis-operator.v0.10.0-on-z
defaultChannel: alpha

