apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemis
metadata:
  name: example-activemqartemis
  application: example-activemqartemis-app
  labels:
    ActiveMQArtemis: example-activemqartemis
    application: example-activemqartemis-app
spec:
  deploymentPlan:
    size: 1
    image: docker-registry.default.svc:5000/olm75-0/amq-broker-74-openshift:9.8
    #image: docker-registry.default.svc:5000/entmqbr-2687-0/amq-broker:7.4-5
    #image: registry.redhat.io/amq7/amq-broker:7.4
    #user: adminUser
    #password: adminPass
    role: admin
    requireLogin: false
    clustered: true
    #clusterUser: clusteruser1
    #clusterPassword: clusterpass1
    persistenceEnabled: false
    journalType: nio
    messageMigration: false
  console:
    expose: true
    sslEnabled: true
    sslSecret: ym-secret
    useClientAuth: true
  acceptors:
    #- name: all-protocol
      #protocols: all
      #port: 61616
    - name: my
      protocols: amqp
      port: 5672
      sslEnabled: false
      #sslSecret: ym-secret
      expose: false
  #connectors:
    #- name: my-c
      #host: localhost
      #port: 22222
      #sslEnabled: false
      #sslSecret: c-ym-secret
    #- name: second-c
      #host: 127.0.0.1
      #port: 33333
