apiVersion: broker.amq.io/v1alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: example-activemqartemisaddress
  labels:
    ActiveMQArtemis: example-activemqartemis
    application: example-activemqartemis-app
spec:
  # Add fields here
  addressName: myAddress0
  queueName: myQueue0
  routingType: anycast
