name: CI

env:
  IMAGE_NAME: activemq-artemis-operator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.8'

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Check generate files
        run: make generate-deploy && make bundle && git status && git diff-index --quiet HEAD --

      - name: Execute the tests
        run: make test

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Checkout artemiscloud.github.io
        uses: actions/checkout@v3
        with:
          repository: artemiscloud/artemiscloud.github.io
          path: artemiscloud.github.io

      - name: Build the docs
        run: >
          rm -rf artemiscloud.github.io/content/en/docs &&
          cp -r docs artemiscloud.github.io/content/en &&
          cd artemiscloud.github.io &&
          npm install && npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build the image
        run: |
          podman build --build-arg TARGETOS=linux --build-arg TARGETARCH=amd64 --label quay.expires-after=90d --label git-sha=$GITHUB_SHA --no-cache --platform linux/amd64 --manifest $IMAGE_NAME:dev.latest .
          #podman build --build-arg TARGETOS=linux --build-arg TARGETARCH=arm64 --label quay.expires-after=90d --label git-sha=$GITHUB_SHA --no-cache --platform linux/arm64 --manifest $IMAGE_NAME:dev.latest .

      - name: Push the dev image
        if: ${{ github.event_name == 'push' }}
        run: |
          IMAGE_TAG=dev.$(date +%Y%m%d).$(git rev-parse --short "$GITHUB_SHA")
          podman login --username=${{ secrets.QUAY_USERNAME }} --password=${{ secrets.QUAY_PASSWORD }} quay.io
          podman manifest push $IMAGE_NAME:dev.latest docker://quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:dev.latest
          podman manifest push $IMAGE_NAME:dev.latest docker://quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Build the bundle image
        run: export BUNDLE_IMG=$IMAGE_NAME-bundle:dev.latest && make bundle-build

      - name: Push the bundle image
        if: ${{ github.event_name == 'push' }}
        run: >
          export IMAGE_TAG=dev.$(date +%Y%m%d).$(git rev-parse --short "$GITHUB_SHA") &&
          docker login quay.io --username=${{ secrets.QUAY_USERNAME }} --password-stdin <<< ${{ secrets.QUAY_PASSWORD }} &&
          docker tag $IMAGE_NAME-bundle:dev.latest quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME-bundle:$IMAGE_TAG &&
          docker push quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME-bundle:$IMAGE_TAG &&
          docker tag $IMAGE_NAME-bundle:dev.latest quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME-bundle:dev.latest &&
          docker push quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME-bundle:dev.latest
